### ISSUE TITLE
Great Job！

### ISSUE THREAD

**Issue by br-pp** [Piogeon/InDI-implementation#1]
Dear Author,

Thank you for your excellent work! We have recently come across your meaningful paper and are very interested in it. We were wondering if you would consider open-sourcing more details of your code? We are not sure if we have achieved the performance as described in the original paper during our replication efforts.

**Comment by fpramunno** [comment]
Hi,
I am not the author of the paper, I just tried to implement based on their writings, that's why this is an unofficial implementation. Thus I can't open-sourcing more details on the paper results, because I do not have more. Do you have any other question? Thanks!
